eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 8765
spring:
   application:
     name: service-feign
feign:
  hystrix:
    enabled: true


ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
